version: '3.1'

services:
  db:
    image: postgres:13.2
    restart: always
    volumes:
      - ./src/main/resources/db/docker-sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresPwd
    ports:
      - "5432:5432"